import { FieldSchemaBuilder } from '@core/framework/schema/field-schema/field.schema.builder'

export const IdBuilder = new FieldSchemaBuilder(1, 'id').setTypeData('text').setDefaultValue(23)
export const OrderBuilder = new FieldSchemaBuilder(2, 'order')
    .setTypeData('number')
    .setDefaultValue(2)
export const ShowRoomsBuilder = new FieldSchemaBuilder(3, 'selectShowrooms').setTypeData('select')
export const InputTextBuilder = new FieldSchemaBuilder(4, 'inputControl')
    .setTypeData('text')
    .setDefaultValue('Ma valeur')
export const SelectIdBuilder = new FieldSchemaBuilder(5, 'selectOptionsId')
    .setTypeData('select')
    .setDefaultValue(5)
export const CheckBuilder = new FieldSchemaBuilder(6, 'trueFalseValue')
    .setTypeData('checkbox')
    .setDefaultValue(true)
export const DateTimeBuilder = new FieldSchemaBuilder(7, 'dateTimeValue')
    .setTypeData('date')
    .setDefaultValue('24/10/1977')
export const RadioBuilder = new FieldSchemaBuilder(8, 'selectedRadioId')
    .setTypeData('radio')
    .setDefaultValue('value-2')
export const RteBuilder = new FieldSchemaBuilder(9, 'richTextField')
    .setTypeData('richtext')
    .setDefaultValue(
        'IjxlbT5qZSBTdWlzJm5ic3A7PC9lbT4gPHN0cm9uZz5WcmFpbWVudDwvc3Ryb25nPiA8cz5UcuhzIENvb2w8L3M+Ig=='
    )
export const RangeBuilder = new FieldSchemaBuilder(10, 'rangeSlider')
    .setTypeData('range')
    .setDefaultValue('25')
export const UserIdBuilder = new FieldSchemaBuilder(11, 'userName')
    .setTypeData('text')
    .setDefaultValue('Tadeo')
export const PasswordBuilder = new FieldSchemaBuilder(12, 'password')
    .setTypeData('text')
    .setDefaultValue('my super password')
export const ToggleBuilder = new FieldSchemaBuilder(13, 'toggle')
    .setTypeData('toggle')
    .setDefaultValue(true)
export const Toggle2Builder = new FieldSchemaBuilder(14, 'toggle2')
    .setTypeData('toggle')
    .setDefaultValue(true)
